-- Migration 029: Fix BNM and PDPC seeded titles that migration 028 missed
-- (028 matched 'PDPC update #N' / 'BNM regulation #N' but seeded titles were
--  'PDPC clarification #N' / 'BNM policy update #N')

UPDATE regwatch.changes
SET
  title = CASE title
    WHEN 'BNM policy update #1' THEN 'BNM Policy Document on Risk Management in Technology — 2025 Revision'
    WHEN 'BNM policy update #2' THEN 'BNM Policy Document on Outsourcing — Enhanced Third-Party Risk Requirements'
    WHEN 'BNM policy update #3' THEN 'BNM Climate Change and Principle-based Taxonomy — Revised Sector Classification'
    WHEN 'BNM policy update #4' THEN 'BNM Consultation Paper on Digital Insurance and Takaful'
    WHEN 'BNM policy update #5' THEN 'BNM Financial Services Act Cyber Incident Reporting Framework 2025'
    WHEN 'BNM policy update #6' THEN 'BNM Policy Document on Operational Risk — Business Continuity Management'
    WHEN 'BNM policy update #7' THEN 'BNM Anti-Money Laundering and Counter Financing of Terrorism Policy 2024 Update'
    WHEN 'BNM policy update #8' THEN 'BNM Guideline on Electronic Know Your Customer (e-KYC) — Enhanced Due Diligence'
    WHEN 'PDPC clarification #1' THEN 'PDPC Advisory Guidelines on AI — Recommendation Systems in Financial Services'
    WHEN 'PDPC clarification #2' THEN 'PDPC Enforcement Direction — Financial Sector Data Breach Notification Timeliness'
    WHEN 'PDPC clarification #3' THEN 'PDPC Guide on Data Protection Practices for Digital Financial Services'
    WHEN 'PDPC clarification #4' THEN 'PDPC Mandatory Data Protection Officer Requirements — Enhanced Annual Review'
    WHEN 'PDPC clarification #5' THEN 'PDPC NRIC Handling Guidance — Identity Data in Financial Onboarding Revised'
    WHEN 'PDPC clarification #6' THEN 'PDPC Research Publication — Privacy-Enhancing Technologies for Financial Data Sharing'
    WHEN 'PDPC clarification #7' THEN 'PDPC Advisory Guidelines — International Data Transfers and Binding Corporate Rules'
    WHEN 'PDPC clarification #8' THEN 'PDPC Financial Penalty Framework — Repeat Offender Provisions'
    ELSE title
  END,
  summary = CASE title
    WHEN 'BNM policy update #1' THEN $rw$BNM has issued a revised policy document on technology risk management for licensed institutions, updating requirements around cloud computing, cyber resilience, and third-party software risk. Institutions must complete a gap assessment against the updated policy within 6 months of publication. Board-approved IT risk appetite statements are now mandatory for all licensed commercial banks and insurers.$rw$
    WHEN 'BNM policy update #2' THEN $rw$BNM has revised the policy document on outsourcing to strengthen oversight of cloud service providers and critical third-party processors. Licensed institutions must conduct enhanced due diligence on offshore outsourcing arrangements and assess jurisdiction-specific legal risks. Existing material outsourcing arrangements must be reviewed within 12 months of the revised policy effective date.$rw$
    WHEN 'BNM policy update #3' THEN $rw$BNM has updated sector-level classifications under the CCPT to align with ASEAN Taxonomy for Sustainable Finance v2 and extend coverage to professional services and supply chain finance. Institutions must re-classify their green financing portfolios under the revised taxonomy and update regulatory reporting by Q2 2025. The revision introduces a Watch List category for high-transition-risk exposures.$rw$
    WHEN 'BNM policy update #4' THEN $rw$BNM has issued a consultation paper proposing a regulatory framework for digital insurers and takaful operators offering mobile-first, on-demand insurance products. The framework proposes simplified licensing, data protection obligations, and AI governance requirements for digital underwriting engines. Feedback on the consultation paper is due by 31 August 2025.$rw$
    WHEN 'BNM policy update #5' THEN $rw$BNM has published a new cyber incident reporting framework under the Financial Services Act 2013, requiring licensed institutions to notify BNM within 1 hour of detecting a material cyber incident. The framework defines materiality thresholds based on customer impact, system criticality, and regulatory data exposure. Institutions must update their incident response playbooks and BNM contact procedures by 30 June 2025.$rw$
    WHEN 'BNM policy update #6' THEN $rw$BNM has revised its policy document on operational risk management to require licensed institutions to formalise a resilience testing programme covering severe but plausible scenarios including ransomware and cloud outage. Institutions must conduct a sector-wide table-top exercise facilitated by BNM and submit an after-action report within 30 days. Updated business continuity plans must be approved by the board annually.$rw$
    WHEN 'BNM policy update #7' THEN $rw$BNM has issued updated AML/CFT policy requirements incorporating FATF 2024 standards on virtual asset service providers and proliferation financing. Licensed institutions must implement risk-based controls for politically exposed persons in digital onboarding workflows. Enhanced transaction monitoring rules for cross-border remittances above MYR 50,000 must be implemented by 1 January 2026.$rw$
    WHEN 'BNM policy update #8' THEN $rw$BNM has updated its e-KYC guideline to permit liveness detection and facial biometrics for customer onboarding without physical verification for low-risk segments. Institutions adopting e-KYC must conduct annual technology audits of their identity verification providers and submit summary results to BNM. Enhanced due diligence requirements remain mandatory for high-risk customers regardless of onboarding channel.$rw$
    WHEN 'PDPC clarification #1' THEN $rw$The PDPC has issued advisory guidelines on responsible AI, focusing on algorithmic recommendation systems used by financial institutions for product cross-selling. Institutions must implement opt-out mechanisms for profiling-based product recommendations and provide transparency notices at point of interaction. A compliance checklist for recommendation system operators is available on the PDPC website.$rw$
    WHEN 'PDPC clarification #2' THEN $rw$The PDPC has issued an enforcement direction following investigations into multiple financial sector data breaches where notification timelines exceeded the mandatory 3-business-day requirement. Financial institutions are reminded that the Personal Data Protection (Amendment) Act 2020 requires notification for breaches affecting 500 or more individuals within 3 business days of assessment. Recurring non-compliance may result in financial penalties up to S$1 million.$rw$
    WHEN 'PDPC clarification #3' THEN $rw$The PDPC has published a sector-specific guide on data protection for digital financial services including neobanks, P2P lenders, and insurtech platforms. Key recommendations include privacy-by-design implementation, data minimisation for e-KYC, and consent management for behavioural analytics. The guide supplements MAS TRM Guidelines and should be read together with PDPC's Accountability and Transparency Advisory.$rw$
    WHEN 'PDPC clarification #4' THEN $rw$The PDPC has strengthened requirements for Data Protection Officers (DPOs) in financial institutions, mandating annual DPO competency assessments and public disclosure of DPO contact details. Organisations with more than 250 employees in Singapore must register their DPO with the PDPC by 31 January 2026. The PDPC's online DPO Competency Framework Assessment tool must be used for the annual review.$rw$
    WHEN 'PDPC clarification #5' THEN $rw$The PDPC has revised its advisory on NRIC collection in financial customer onboarding, permitting collection for MAS-regulated KYC purposes without prior consent. However, NRIC data must be treated as sensitive personal data with enhanced retention controls and access logging. Financial institutions must update their data protection impact assessments for onboarding processes by 30 June 2025.$rw$
    WHEN 'PDPC clarification #6' THEN $rw$The PDPC has published research on privacy-enhancing technologies (PETs) suitable for financial data sharing in the MAS Open Banking framework. Technologies covered include differential privacy, synthetic data generation, secure multi-party computation, and homomorphic encryption. The publication includes implementation guidance for financial institutions piloting PETs in data analytics.$rw$
    WHEN 'PDPC clarification #7' THEN $rw$The PDPC has updated advisory guidelines on international data transfers, introducing a model for Binding Corporate Rules (BCRs) for multinational financial groups with Singapore operations. Financial groups may use BCRs as an adequacy mechanism for intragroup transfers subject to PDPC approval. Applications for BCR recognition must be submitted by 1 September 2025 to qualify for the first assessment cycle.$rw$
    WHEN 'PDPC clarification #8' THEN $rw$The PDPC has announced a revised penalty framework under section 48J of the PDPA for repeat offenders in the financial sector, with penalties scaling to S$1 million for third and subsequent breaches within a 5-year period. Mitigating factors include voluntary notification, prior compliance investment, and DPO certification. The framework applies to investigations commenced after 1 October 2025.$rw$
    ELSE summary
  END
WHERE title ~ '#[0-9]+$';
