-- Migration 055: Add framework assessments for 5 small tenants.
-- Large tenants (Grab, Maybank, MINDEF) have 8 assessments each.
-- Small tenants have only 2 (soc2, iso-27001). Adding 6 relevant
-- assessments per tenant based on industry context.
-- Note: compliance.framework_score is a VIEW over compliance.assessments.
-- Idempotent: INSERT ... WHERE NOT EXISTS.

INSERT INTO compliance.assessments
  (tenant_id, framework_id, status, score, started_at, next_due_at, created_at)
SELECT v.tenant_id, v.framework_id, v.status::compliance.assessment_status,
       v.score, v.started_at, v.next_due_at, v.created_at
FROM (VALUES
  -- A*STAR (Research)
  ('t_astar','mas-trm','complete',
   (72 + abs(hashtext('t_astar_mas_trm')) % 22)::numeric(5,2),
   now() - interval '90 days', now() + interval '180 days',
   now() - interval '100 days'),
  ('t_astar','pdpa-sg','in-progress',
   (70 + abs(hashtext('t_astar_pdpa_sg')) % 25)::numeric(5,2),
   now() - interval '30 days', now() + interval '90 days',
   now() - interval '35 days'),
  ('t_astar','nist-csf','complete',
   (74 + abs(hashtext('t_astar_nist_csf')) % 20)::numeric(5,2),
   now() - interval '60 days', now() + interval '365 days',
   now() - interval '70 days'),
  ('t_astar','iso-42001','in-progress',
   (65 + abs(hashtext('t_astar_iso_42001')) % 28)::numeric(5,2),
   now() - interval '45 days', now() + interval '120 days',
   now() - interval '50 days'),
  ('t_astar','iso-27018','complete',
   (78 + abs(hashtext('t_astar_iso_27018')) % 18)::numeric(5,2),
   now() - interval '120 days', now() + interval '270 days',
   now() - interval '130 days'),
  ('t_astar','nist-airmf','in-progress',
   (68 + abs(hashtext('t_astar_nist_airmf')) % 24)::numeric(5,2),
   now() - interval '20 days', now() + interval '150 days',
   now() - interval '25 days'),

  -- GovTech (Public Sector)
  ('t_govtech','im8','complete',
   (85 + abs(hashtext('t_govtech_im8')) % 14)::numeric(5,2),
   now() - interval '180 days', now() + interval '365 days',
   now() - interval '190 days'),
  ('t_govtech','mas-trm','in-progress',
   (76 + abs(hashtext('t_govtech_mas_trm')) % 20)::numeric(5,2),
   now() - interval '40 days', now() + interval '120 days',
   now() - interval '45 days'),
  ('t_govtech','pdpa-sg','complete',
   (88 + abs(hashtext('t_govtech_pdpa_sg')) % 10)::numeric(5,2),
   now() - interval '90 days', now() + interval '180 days',
   now() - interval '100 days'),
  ('t_govtech','nist-csf','complete',
   (82 + abs(hashtext('t_govtech_nist_csf')) % 15)::numeric(5,2),
   now() - interval '120 days', now() + interval '270 days',
   now() - interval '130 days'),
  ('t_govtech','iso-27701','in-progress',
   (71 + abs(hashtext('t_govtech_iso_27701')) % 22)::numeric(5,2),
   now() - interval '25 days', now() + interval '90 days',
   now() - interval '30 days'),
  ('t_govtech','iso-42001','in-progress',
   (69 + abs(hashtext('t_govtech_iso_42001')) % 26)::numeric(5,2),
   now() - interval '15 days', now() + interval '150 days',
   now() - interval '20 days'),

  -- Mediacorp (Media)
  ('t_mediacorp','pdpa-sg','complete',
   (83 + abs(hashtext('t_mediacorp_pdpa_sg')) % 13)::numeric(5,2),
   now() - interval '100 days', now() + interval '180 days',
   now() - interval '110 days'),
  ('t_mediacorp','pdpa-my','in-progress',
   (72 + abs(hashtext('t_mediacorp_pdpa_my')) % 22)::numeric(5,2),
   now() - interval '50 days', now() + interval '120 days',
   now() - interval '55 days'),
  ('t_mediacorp','mas-trm','complete',
   (78 + abs(hashtext('t_mediacorp_mas_trm')) % 18)::numeric(5,2),
   now() - interval '80 days', now() + interval '270 days',
   now() - interval '90 days'),
  ('t_mediacorp','nist-csf','in-progress',
   (70 + abs(hashtext('t_mediacorp_nist_csf')) % 24)::numeric(5,2),
   now() - interval '35 days', now() + interval '90 days',
   now() - interval '40 days'),
  ('t_mediacorp','iso-27701','complete',
   (80 + abs(hashtext('t_mediacorp_iso_27701')) % 16)::numeric(5,2),
   now() - interval '130 days', now() + interval '365 days',
   now() - interval '140 days'),
  ('t_mediacorp','csrd','in-progress',
   (60 + abs(hashtext('t_mediacorp_csrd')) % 30)::numeric(5,2),
   now() - interval '20 days', now() + interval '150 days',
   now() - interval '25 days'),

  -- SingHealth (Healthcare)
  ('t_singhealth','mas-trm','complete',
   (80 + abs(hashtext('t_singhealth_mas_trm')) % 16)::numeric(5,2),
   now() - interval '90 days', now() + interval '180 days',
   now() - interval '100 days'),
  ('t_singhealth','pdpa-sg','complete',
   (87 + abs(hashtext('t_singhealth_pdpa_sg')) % 11)::numeric(5,2),
   now() - interval '150 days', now() + interval '270 days',
   now() - interval '160 days'),
  ('t_singhealth','hipaa','in-progress',
   (74 + abs(hashtext('t_singhealth_hipaa')) % 20)::numeric(5,2),
   now() - interval '60 days', now() + interval '120 days',
   now() - interval '65 days'),
  ('t_singhealth','nist-csf','complete',
   (82 + abs(hashtext('t_singhealth_nist_csf')) % 14)::numeric(5,2),
   now() - interval '120 days', now() + interval '365 days',
   now() - interval '130 days'),
  ('t_singhealth','iso-27701','in-progress',
   (76 + abs(hashtext('t_singhealth_iso_27701')) % 20)::numeric(5,2),
   now() - interval '45 days', now() + interval '90 days',
   now() - interval '50 days'),
  ('t_singhealth','iso-22301','complete',
   (84 + abs(hashtext('t_singhealth_iso_22301')) % 12)::numeric(5,2),
   now() - interval '75 days', now() + interval '150 days',
   now() - interval '85 days'),

  -- Singtel (Telecommunications)
  ('t_singtel','mas-trm','complete',
   (84 + abs(hashtext('t_singtel_mas_trm')) % 14)::numeric(5,2),
   now() - interval '100 days', now() + interval '270 days',
   now() - interval '110 days'),
  ('t_singtel','dora','in-progress',
   (71 + abs(hashtext('t_singtel_dora')) % 24)::numeric(5,2),
   now() - interval '55 days', now() + interval '120 days',
   now() - interval '60 days'),
  ('t_singtel','pdpa-sg','complete',
   (86 + abs(hashtext('t_singtel_pdpa_sg')) % 12)::numeric(5,2),
   now() - interval '120 days', now() + interval '180 days',
   now() - interval '130 days'),
  ('t_singtel','nist-csf','complete',
   (80 + abs(hashtext('t_singtel_nist_csf')) % 16)::numeric(5,2),
   now() - interval '90 days', now() + interval '365 days',
   now() - interval '100 days'),
  ('t_singtel','nis2','in-progress',
   (68 + abs(hashtext('t_singtel_nis2')) % 26)::numeric(5,2),
   now() - interval '30 days', now() + interval '90 days',
   now() - interval '35 days'),
  ('t_singtel','iso-22301','complete',
   (83 + abs(hashtext('t_singtel_iso_22301')) % 14)::numeric(5,2),
   now() - interval '70 days', now() + interval '150 days',
   now() - interval '80 days')
) AS v(tenant_id, framework_id, status, score, started_at, next_due_at, created_at)
WHERE NOT EXISTS (
  SELECT 1 FROM compliance.assessments a
  WHERE a.tenant_id = v.tenant_id AND a.framework_id = v.framework_id
);
